- name: delete app directory
  ansible.builtin.file:
    path: "{{ app_location }}"
    state: absent
  #ignore_errors: yes

- name: create app directory
  ansible.builtin.file:
    path: "{{ app_location }}"
    state: directory


####  if we are not using the nexus- we should directrly download the code form the s3 bucket.
# - name: download and extract code
#   ansible.builtin.unarchive:
#     src: "https://expense-builds.s3.us-east-1.amazonaws.com/expense-{{ component }}-v2.zip"
#     dest: "{{ app_location }}"
#     remote_src: yes

### make sure src is correctly configured as per the nexus artifact URL
- name: download the artifact from nexus
  ansible.builtin.unarchive:
    src: "http://{{ nexus_url }}/repository/{{ component }}/com/expense/{{ component }}/{{ appVersion }}/{{ component }}-{{ appVersion }}.zip"
    dest: "{{ app_location }}"
    remote_src: yes